### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by overthink** [mj-wang/Sortable-Coding-2015#1]
Hi Mengyin.  I'm trying to evaluate your solution, but it's throwing:

```
python sortable_challenge_code_cln.py ../listings.txt ../products.txt ./results.txt
Traceback (most recent call last):
  File "sortable_challenge_code_cln.py", line 145, in <module>
    matcher.analysis_and_matching()
  File "sortable_challenge_code_cln.py", line 85, in analysis_and_matching
    self.listings_df = self.listings_df.drop('listings_vec', 1)
  File "/usr/lib/pymodules/python2.7/pandas/core/generic.py", line 174, in drop
    new_axis = axis.drop(labels)
  File "/usr/lib/pymodules/python2.7/pandas/core/index.py", line 881, in drop
    raise ValueError('labels %s not contained in axis' % labels[mask])
ValueError: labels [l i s t i n g s _ v e c] not contained in axis
```

Let me know when you fix this up and I'll take another look!
Thanks,

Mark (from sortable.com)

**Comment by mj-wang** [comment]
Hey Mark,

That interesting-I don't get that error on my computer. I've removed the
lines causing that problem and committed the change on GitHub.

Cheers,
Mengyin Wang
